;;These are the libraries we need
(ns cortex.prepare
  (:require [clojure.java.io :as io]
            [mikera.image.filters :as filters]
            [mikera.image.core :as imagez]
            [clojure.string :as string]))

;;Takes in directory to folder
;;Returns a collection of all images within said folder
(defn- gather-files
  [path]
  (->> (io/file path)
       (file-seq)
       (filter #(.isFile %))))

;;Takes in collection of images
;;Returns a collection containing elements in this form: [file-index [image image-label]]
(defn- indexed-data-label-seq
  [files]
  (->> (map (fn [file] [file (-> (.getName file) (string/split #"\.") first)]) files)
       (map-indexed vector)))

;;Takes in: i)Output directory ii)New image size iii)An element representing an image from
;;the collection generated by above function
;;Returns: Saves image in output directory after turning it greyscale and scaling it to
;;image-size x image-size dimensions
(defn img-preprocess
  [output-dir image-size [idx [file label]]]
  (let [img-path (str output-dir "/" label "/" idx ".png")]
    (when-not (.exists (io/file img-path))
      (println "> " img-path)
      (io/make-parents img-path)
      (-> (imagez/load-image file)
          ((filters/grayscale))
          (imagez/resize image-size image-size)
          (imagez/save img-path)))))

;;Similar to img-preprocess function. But this function will be used
;;for preprocessing and saving test images. But name format of these
;;images will be just like that of images in train folder
(defn img-preprocess-test
  [output-dir image-size [idx [file label]]]
  (let [img-path (str output-dir "/" label "." idx ".png")]
    (when-not (.exists (io/file img-path))
      (println "> " img-path)
      (io/make-parents img-path)
      (-> (imagez/load-image file)
          ((filters/grayscale))
          (imagez/resize image-size image-size)
          (imagez/save img-path)))))

;;Takes in: i)directory of folder containing colored, unresized images ii)directory
;;where processed training images will be saved iii)directory where validation images
;;will be saved iv) directory where test images
;;will be saved v) New image width and height
;;Returns: Generates processed training, validation and test image dataset in 3:1:1 ratio using
;;functions above
;;Tip-'pmap' is used for parallelizing image preprocessing, hence speeding up
;;the process.
(defn build-image-data
  [original-dir training-dir valid-dir test-dir img-size]
  (let [files (gather-files original-dir)
        pfiles (partition (int (/ (count files) 5)) (shuffle files))
        test-labels (indexed-data-label-seq (first pfiles))
        valid-labels (indexed-data-label-seq (first (rest pfiles)))
        training-labels (indexed-data-label-seq (apply concat (rest (rest pfiles))))
        train-fn (partial img-preprocess training-dir img-size)
        valid-fn (partial img-preprocess valid-dir img-size)
        test-fn (partial img-preprocess-test test-dir img-size)]
    (dorun (pmap train-fn training-labels))
    (dorun (pmap valid-fn valid-labels))
    (dorun (pmap test-fn test-labels))))






